name: Server Lint

on:
  push:
  pull_request:
    branches:
      - master
    paths:
      - server/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: server/
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        working-directory: server/